export const GET_HOTELS_PENDING = 'GET_HOTELS_PENDING';
export const GET_HOTELS_SUCCESS = 'GET_HOTELS_SUCCESS';
export const GET_HOTELS_FAIL = 'GET_HOTELS_FAIL';

export const GET_HOTEL_PENDING = 'GET_HOTEL_PENDING';
export const GET_HOTEL_SUCCESS = 'GET_HOTEL_SUCCESS';
export const GET_HOTEL_FAIL = 'GET_HOTEL_FAIL';

export const GET_COUNTRIES_PENDING = 'GET_COUNTRIES_PENDING';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_COUNTRIES_FAIL = 'GET_COUNTRIES_FAIL';

export const GET_COUNTRY_PENDING = 'GET_COUNTRY_PENDING';
export const GET_COUNTRY_SUCCESS = 'GET_COUNTRY_SUCCESS';
export const GET_COUNTRY_FAIL = 'GET_COUNTRY_FAIL';

export const ADD_COUNTRY_PENDING = 'ADD_COUNTRY_PENDING';
export const ADD_COUNTRY_SUCCESS = 'ADD_COUNTRY_SUCCESS';
export const ADD_COUNTRY_FAIL = 'ADD_COUNTRY_FAIL';
