export const GET_HOTELS_PENDING = 'GET_HOTELS_PENDING';
export const GET_HOTELS_SUCCESS = 'GET_HOTELS_SUCCESS';
export const GET_HOTELS_FAIL = 'GET_HOTELS_FAIL';

export const GET_HOTEL_PENDING = 'GET_HOTEL_PENDING';
export const GET_HOTEL_SUCCESS = 'GET_HOTEL_SUCCESS';
export const GET_HOTEL_FAIL = 'GET_HOTEL_FAIL';
